arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: base_link_to_base_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: base_joint_to_first_arm_joint_right
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: first_joint_to_second_arm_joint_right
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: second_joint_to_third_arm_joint_right
    pid: {p: 100.0, i: 0.01, d: 10.0}

  finger1_position_controller:
    type: position_controllers/JointPositionController
    joint: zhuazi_base_to_zhuazi_left
    pid: {p: 100.0, i: 0.01, d: 10.0}

  finger2_position_controller:
    type: position_controllers/JointPositionController
    joint: zhuazi_base_to_zhuazi_right
    pid: {p: 100.0, i: 0.01, d: 10.0}
 
