joint_limits:
  base_link_to_base_joint:
    has_position_limits: flase
    has_velocity_limits: flase

    base_joint_to_first_arm_joint_right:
      has_position_limits: true
      min_position: -2.6
      max_position: 2.6
      has_velocity_limits: true
      max_velocity: 0.1

    first_joint_to_second_arm_joint_right:
      has_position_limits: true
      min_position: -2.6
      max_position: 2.6
      has_velocity_limits: true
      max_velocity: 0.1

    second_joint_to_third_arm_joint_right:
      has_position_limits: true
      min_position: -2.6
      max_position: 2.6
      has_velocity_limits: true
      max_velocity: 0.1

    zhuazi_base_to_zhuazi_left:
      has_position_limits: true
      min_position: 0
      max_position: 0.05
      has_velocity_limits: true
      max_velocity: 0.1

    zhuazi_base_to_zhuazi_right:
      has_position_limits: true
      min_position: 0
      max_position: 0.05
      has_velocity_limits: true
      max_velocity: 0.1
    