obstacle_range: 2.5  
raytrace_range: 3.0  
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]  
robot_radius: 0.4
inflation_radius: 0.25
  
observation_sources: laser_scan_sensor point_cloud_sensor  
laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}  
  